# -*- coding: utf-8 -*-
"""CMPE331.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/101z0tUmCG9U_Bm4bqSfMATIxsF1oPIgA

Stage: Development 01
@author: E. Esin YILMAZ, 120200059
@author: Ahmet Kıvanç DEMIRKIRAN, 120200133
"
"""

html_doc="https://www.airbnb.com.tr/?_set_bev_on_new_domain=1669973802_NTQ0MTg1YmUyYmM2"

def scrape_page(page_url):
    """Extracts HTML from a webpage"""
    
    answer = requests.get(URL)
    content = answer.content
    soup = BeautifulSoup(content, features='html.parser')
    
    return soup

def extract_element_data(soup, params):
	    """Extracts data from a specified HTML element"""
	    
	    # 1. Find the right tag
      if 'class' in params:
	        elements_found = soup.find_all(params['tag'], params['class'])
	    else:
	        elements_found = soup.find_all(params['tag'])
	        
	    # 2. Extract text from these tags
	    if 'get' in params:
	        element_texts = [el.get(params['get']) for el in elements_found]
	    else:
	        element_texts = [el.get_text() for el in elements_found]
	        
	    # 3. Select a particular text or concatenate all of them
	    tag_order = params.get('order', 0)
	    if tag_order == -1:
	        output = '**__**'.join(element_texts)
	    else:
	        output = element_texts[tag_order]
	    
	    return output





